version: "3"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: myPassword
      MYSQL_DATABASE: EnvironmentMonitor
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: backend
    restart: always
    environment:
      - MAPS_API_KEY=${MAPS_API_KEY}
      - MELB_CBD_LAT=${MELB_CBD_LAT}
      - MELB_CBD_LNG=${MELB_CBD_LNG}
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    build:
      context: frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  db-data:
